### ISSUE TITLE
prepare brew for OS X

### ISSUE THREAD

**Issue by peak-load** [eduvpn/macos#100]
It will be nice to have brew for this project

**Comment by fkooman** [comment]
Do you have any experience creating those? Looking for example at the one for Tunnelblick doesn't really look that interesting: it is just a "wrapper" around the binary.

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/tunnelblick.rb

**Comment by bric3** [comment]
Just in case I just created a PR adding the eduVPN formula : https://github.com/Homebrew/homebrew-cask/pull/58456

**Comment by 404NetworkError** [comment]
@fkooman Since @bric3's PR in the main Homebrew repo got [rejected](https://github.com/Homebrew/homebrew-cask/pull/58456#issuecomment-460879690), I would suggest creating the `eduvpn/homebrew-eduvpn` tap repo. (If you want an example tap, I would look at [AdoptOpenJDK's tap](https://github.com/AdoptOpenJDK/homebrew-openjdk).)

Anyways, here is a complete `Casks/eduvpn.rb` file to help you out:
```
cask 'eduvpn' do
  version '1.1'
  sha256 '7cf102702de2c8f3d83378399d6f48d12b20a8261d4f61702dca0d2277c192ba'

  url "https://app.eduvpn.nl/mac/eduVPN_#{version}.dmg"
  appcast 'https://app.eduvpn.nl/mac/appcast.xml'
  name 'eduVPN'
  homepage 'https://app.eduvpn.nl/'

  auto_updates true
  depends_on macos: '>= :sierra'

  app 'eduVPN.app'

  zap trash: [
               '~/Library/Application Support/eduVPN',
               '~/Library/Preferences/org.eduvpn.app.plist',
             ]
end
```
Then, it's just a simple `brew tap eduvpn/eduvpn` and `brew cask install eduvpn`.
