### ISSUE TITLE
disconnect - connect errors

### ISSUE THREAD

**Issue by efef** [eduvpn/macos#134]
When I disconnect a running session and quickly re-connect. I get strange errors. Sometimes the connection disconnects within a second. Sometimes  error notifications.
<img width="436" alt="screen shot 2018-09-28 at 15 44 14" src="https://user-images.githubusercontent.com/3393474/46212311-f7a0e580-c335-11e8-97fa-a407387ac264.png">
<img width="435" alt="screen shot 2018-09-28 at 15 46 05" src="https://user-images.githubusercontent.com/3393474/46212324-fe2f5d00-c335-11e8-857e-71fa197c841f.png">

**Comment by johankool** [comment]
The down script resets the DNS by turning the Wifi off and back on again. That explains at least the second dialog. I suppose I could add a "cool down" period after disconnecting so that users can't quickly press connect again.

The "Helper rejected request" is odd, that should only happen when the signature of the OpenVPN binary or the scrips has changed.
